# Environment variables expected for the app to run
# Custom connection strings or secrets
AZUREML_SERVICE_PRINCIPAL_SECRET_ENVIRONMENT_VARIABLE = "CUSTOMCONNSTR_AZUREML_SERVICE_PRINCIPAL_SECRET"
API_AUTH_SECRET_ENVIRONMENT_VARIABLE = "CUSTOMCONNSTR_API_AUTH_SECRET"

# Configurations
CLUSTER = "CLUSTER"
WORKSPACE_NAME = "WORKSPACE_NAME"
EXPERIMENT_NAME = "EXPERIMENT_NAME"
RESOURCE_GROUP = "RESOURCE_GROUP"
SUBSCRIPTION_ID = "SUBSCRIPTION_ID"
APPLICATION_ID = "APPLICATION_ID"
TENANT_ID = "TENANT_ID"
DATASTORE_NAME = "DATASTORE_NAME"
IMAGE_DATA_FOLDER = "IMAGE_DATA_FOLDER"
