# File: .github/workflows/workflow.yml

on:
  push:

name: Deploy to DEV

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Check curl version
      run: curl -V

    #
    # Create a repository dispatch event.
    #
    # https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event
    # This requires a github user with a personal access token:
    # https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token
    # and ensuring that the personal access token is authorized to access the repo https://github.com/microsoft/InnerEye-Gateway/
    # https://docs.github.com/en/github/authenticating-to-github/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on
    # Store the user in the secret DISPATCH_GATEWAY_USER and the access token in the secret DISPATCH_GATEWAY_TOKEN.
    #
    - name: Send remote-dispatch to InnerEye-Gateway
      env:
        USER: ${{ secrets.DISPATCH_GATEWAY_USER }}
        TOKEN: ${{ secrets.DISPATCH_GATEWAY_TOKEN }}
      run: |
        curl \
          --request POST \
          --header "Accept:\ application/vnd.github.v3+json" \
          --user ${USER}:${TOKEN} \
          --data '{"event_type":\ "deploy_to_dev"}' \
          --verbose \
          https://api.github.com/repos/microsoft/InnerEye-Gateway/dispatches
